kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcp-project-operator
subjects:
- kind: ServiceAccount
  name: gcp-project-operator
  # Replace this with the namespace the operator is deployed in.
  namespace: gcp-project-operator
roleRef:
  kind: ClusterRole
  name: gcp-project-operator
  apiGroup: rbac.authorization.k8s.io
