apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gcp-project-operator-client
subjects:
- kind: ServiceAccount
  namespace: gcp-project-operator-client
  name: gcp-project-operator-client
- kind: Group
  name: gcp-project-operator-client
roleRef:
  kind: ClusterRole
  name: gcp-project-operator-client
  apiGroup: rbac.authorization.k8s.io
